/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nusgapcalc;

import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Arm_AVI
 */
public class UISgpaNU extends javax.swing.JFrame {

    /**
     * Creates new form UISgpaNU
     */
    public UISgpaNU() {
        initComponents();
        reSrc.setVisible(false);
        iconInitializer();
    }
    public void iconInitializer(){
    this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subOne = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        subTwo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        subThree = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        subFour = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        subFive = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        subSix = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        subSeven = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        subEight = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        subNine = new javax.swing.JComboBox<>();
        subTwoCre = new javax.swing.JComboBox<>();
        subThreeCre = new javax.swing.JComboBox<>();
        subFourCre = new javax.swing.JComboBox<>();
        subFiveCre = new javax.swing.JComboBox<>();
        subSixCre = new javax.swing.JComboBox<>();
        subSevenCre = new javax.swing.JComboBox<>();
        subEightCre = new javax.swing.JComboBox<>();
        subNineCre = new javax.swing.JComboBox<>();
        subOneCre = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        subTen = new javax.swing.JComboBox<>();
        subTenCre = new javax.swing.JComboBox<>();
        subTwelve = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        subTwelveCre = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        resultDisp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comtMark = new javax.swing.JLabel();
        reSrc = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("National University SGPA/CGPA Calc");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arm_AVI\\Desktop\\Practice\\Java_Prac\\NUSgapCalc\\assestArm\\logo_nu.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("National University");

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SGPA/CGPA Calculator ");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jButton1.setText("Important Link");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jButton2.setText("Calculation Chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jButton3.setText("About");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel19.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Theoretical Subject Credit Hour : 3.00");

        jLabel20.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Practical Subject Credit Hour: 1.5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credit Hour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Subject 1: ");

        subOne.setBackground(new java.awt.Color(255, 0, 0));
        subOne.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Subject 2:");

        subTwo.setBackground(new java.awt.Color(255, 0, 0));
        subTwo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Subject 3:");

        subThree.setBackground(new java.awt.Color(255, 0, 0));
        subThree.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subThree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Subject 4:");

        subFour.setBackground(new java.awt.Color(255, 0, 0));
        subFour.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subFour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("Subject 5:");

        subFive.setBackground(new java.awt.Color(255, 0, 0));
        subFive.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subFive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Subject 6:");

        subSix.setBackground(new java.awt.Color(255, 0, 0));
        subSix.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subSix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Subject 7:");

        subSeven.setBackground(new java.awt.Color(255, 0, 0));
        subSeven.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subSeven.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Subject 8:");

        subEight.setBackground(new java.awt.Color(255, 0, 0));
        subEight.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subEight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setText("Subject 9:");

        subNine.setBackground(new java.awt.Color(255, 0, 0));
        subNine.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subNine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        subTwoCre.setBackground(new java.awt.Color(0, 0, 204));
        subTwoCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTwoCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subThreeCre.setBackground(new java.awt.Color(0, 0, 204));
        subThreeCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subThreeCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subFourCre.setBackground(new java.awt.Color(0, 0, 204));
        subFourCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subFourCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subFiveCre.setBackground(new java.awt.Color(0, 0, 204));
        subFiveCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subFiveCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subSixCre.setBackground(new java.awt.Color(0, 0, 204));
        subSixCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subSixCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subSevenCre.setBackground(new java.awt.Color(0, 0, 204));
        subSevenCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subSevenCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subEightCre.setBackground(new java.awt.Color(0, 0, 204));
        subEightCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subEightCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subNineCre.setBackground(new java.awt.Color(0, 0, 204));
        subNineCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subNineCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subOneCre.setBackground(new java.awt.Color(0, 0, 204));
        subOneCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subOneCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setText("Subject 10:");

        subTen.setBackground(new java.awt.Color(255, 0, 0));
        subTen.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        subTenCre.setBackground(new java.awt.Color(0, 0, 204));
        subTenCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTenCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        subTwelve.setBackground(new java.awt.Color(255, 0, 0));
        subTwelve.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTwelve.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "D", "F" }));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setText("Subject 11:");

        subTwelveCre.setBackground(new java.awt.Color(0, 0, 204));
        subTwelveCre.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        subTwelveCre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "3.00", "1.5" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        resultDisp.setEditable(false);
        resultDisp.setBackground(new java.awt.Color(204, 204, 204));
        resultDisp.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        jButton5.setText("Clear Field");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 13)); // NOI18N
        jButton6.setText("Print Your Mark In Text");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 11)); // NOI18N
        jLabel6.setText("Type Name :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultDisp)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(name)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(resultDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Comment Suggesstions"));

        comtMark.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        reSrc.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        reSrc.setText("Resourses");
        reSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reSrcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comtMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reSrc)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comtMark, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reSrc, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Copyright © 2017. Arunav Mallik Avi (Arm Avi). All rights reserved");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jMenu1.setText("Option");
        jMenu1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jMenuItem2.setText("Clear Field");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subTen, 0, 129, Short.MAX_VALUE)
                                    .addComponent(subTwelve, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(35, 35, 35)
                                    .addComponent(subNine, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(subSix, 0, 129, Short.MAX_VALUE)
                                        .addComponent(subFour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subOne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subTwo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subThree, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subFive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subSeven, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subEight, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subOneCre, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subTwoCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subThreeCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subFourCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subFiveCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subSixCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subSevenCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subEightCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subNineCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subTwelveCre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subTenCre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTwelve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subOneCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(subTwoCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subThreeCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subFourCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subFiveCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subSixCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subSevenCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subEightCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subNineCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTenCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTwelveCre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        double put = 0.0;
        double cre1 = 0.0;
        double cre2 = 0.0;
        double cre3 = 0.0;
        double cre4 = 0.0;
        double cre5 = 0.0;
        double cre6 = 0.0;
        double cre7 = 0.0;
        double cre8 = 0.0;
        double cre9 = 0.0;
        double cre10 = 0.0;
        double cre11 = 0.0;
        double addCre;
        
        double add = 0;
        double addTwo = 0;
        double addThree = 0;
        double addFour = 0;
        double addFive = 0;
        double addSix = 0;
        double addSeven = 0;
        double addEight = 0;
        double addNine = 0;
        double addTen = 0;
        double addTwelve = 0;
        double Result;
        
        
        // First Subject 
        if(subOne.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subOne.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subOne.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subOne.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subOne.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subOne.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subOne.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subOne.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subOne.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subOne.getSelectedItem().equals("F")){
          put = 0.00;
        }
       
        // First Subject Credit-----
        if(subOneCre.getSelectedItem().equals("3.00")){
          cre1 = 3.00;
        }
        else if(subOneCre.getSelectedItem().equals("1.5")){
           cre1 = 1.5;
         }
      
        add = put*cre1;
        
        // Second Subject 
         if(subTwo.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subTwo.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subTwo.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subTwo.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subTwo.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subTwo.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subTwo.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subTwo.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subTwo.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subTwo.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Second Subject Credit----
        if(subTwoCre.getSelectedItem().equals("3.00")){
          cre2 = 3.00;
        }
        else if(subTwoCre.getSelectedItem().equals("1.5")){
          cre2 = 1.5;
        }
        addTwo = put*cre2;
        
        
        
        // Third Subject 
         if(subThree.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subThree.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subThree.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subThree.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subThree.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subThree.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subThree.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subThree.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subThree.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subThree.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Third Subject Credit----
        if(subThreeCre.getSelectedItem().equals("3.00")){
          cre3 = 3.00;
        }
        else if(subThreeCre.getSelectedItem().equals("1.5")){
          cre3 = 1.5;
        }
        addThree = put*cre3;
         
        
        // Fourth Subject 
         if(subFour.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subFour.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subFour.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subFour.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subFour.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subFour.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subFour.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subFour.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subFour.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subFour.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Fourth Subject Credit----
        if(subFourCre.getSelectedItem().equals("3.00")){
          cre4 = 3.00;
        }
        else if(subFourCre.getSelectedItem().equals("1.5")){
          cre4 = 1.5;
        }
        addFour = put*cre4;
        
        
         
        // Fifth Subject 
         if(subFive.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subFive.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subFive.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subFive.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subFive.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subFive.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subFive.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subFive.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subFive.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subFive.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Fifth Subject Credit----
        if(subFiveCre.getSelectedItem().equals("3.00")){
          cre5 = 3.00;
        }
        else if(subFiveCre.getSelectedItem().equals("1.5")){
          cre5 = 1.5;
        }
        addFive = put*cre5;
        
        
        // Sixth Subject 
         if(subSix.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subSix.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subSix.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subSix.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subSix.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subSix.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subSix.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subSix.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subSix.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subSix.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Sixth Subject Credit----
        if(subSixCre.getSelectedItem().equals("3.00")){
          cre6 = 3.00;
        }
        else if(subSixCre.getSelectedItem().equals("1.5")){
          cre6 = 1.5;
        }
        addSix = put*cre6;
        
        // Seventh Subject 
         if(subSeven.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subSeven.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subSeven.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subSeven.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subSeven.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subSeven.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subSeven.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subSeven.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subSeven.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subSeven.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Seventh Subject Credit----
        if(subSevenCre.getSelectedItem().equals("3.00")){
          cre7 = 3.00;
        }
        else if(subSevenCre.getSelectedItem().equals("1.5")){
          cre7 = 1.5;
        }
        addSeven = put*cre7;
        
        
        
         // Eighth Subject 
         if(subEight.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subEight.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subEight.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subEight.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subEight.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subEight.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subEight.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subEight.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subEight.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subEight.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Ninth Subject Credit----
        if(subEightCre.getSelectedItem().equals("3.00")){
          cre8 = 3.00;
        }
        else if(subEightCre.getSelectedItem().equals("1.5")){
          cre8 = 1.5;
        }
        addEight = put*cre8;
        
        // Ninth Subject 
         if(subNine.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subNine.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subNine.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subNine.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subNine.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subNine.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subNine.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subNine.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subNine.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subNine.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Ninth Subject Credit----
        if(subNineCre.getSelectedItem().equals("3.00")){
          cre9 = 3.00;
        }
        else if(subNineCre.getSelectedItem().equals("1.5")){
          cre9 = 1.5;
        }
        addNine= put*cre9;
        
        
        // Tenth Subject 
         if(subTen.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subTen.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subTen.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subTen.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subTen.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subTen.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subTen.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subTen.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subTen.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subTen.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Tenth Subject Credit----
        if(subTenCre.getSelectedItem().equals("3.00")){
          cre10 = 3.00;
        }
        else if(subTenCre.getSelectedItem().equals("1.5")){
          cre10 = 1.5;
        }
        addTen= put*cre10;
        
    
         // Twelveth Subject 
         if(subTwelve.getSelectedItem().equals("A+")){
           put = 4;
        }
        else if(subTwelve.getSelectedItem().equals("A")){
          put = 3.75;
        }else if(subTwelve.getSelectedItem().equals("A-")){
          put = 3.50;
        }else if(subTwelve.getSelectedItem().equals("B+")){
          put = 3.25;
        }else if(subTwelve.getSelectedItem().equals("B")){
          put = 3.00;
        }else if(subTwelve.getSelectedItem().equals("B-")){
          put = 2.75;
        }else if(subTwelve.getSelectedItem().equals("C+")){
          put = 2.50;
        }else if(subTwelve.getSelectedItem().equals("C")){
          put = 2.25;
        }else if(subTwelve.getSelectedItem().equals("D")){
          put = 2.00;
        }else if(subTwelve.getSelectedItem().equals("F")){
          put = 0.00;
        }
        
       
        // Twelveth Subject Credit----
        if(subTwelveCre.getSelectedItem().equals("3.00")){
          cre11 = 3.00;
        }
        else if(subTwelveCre.getSelectedItem().equals("1.5")){
          cre11 = 1.5;
        }
        addTwelve= put*cre11;
        
        
        
        
        addCre = cre1 + cre2 + cre3 + cre4 + cre5 + cre6 + cre7 + cre8 + cre9 + cre10 + cre11;
        Result = (add + addTwo+ addThree + addFour + addFive + addSix + addSeven + addEight + addNine + addTen + addTwelve)/(addCre);
        
        
        // Display The Result
        String disp = String.format("%.2f", Result);
           resultDisp.setText(disp);    
           
         if(Result>=3.80 && Result<=4.00){
          comtMark.setText("Briliant Result, The Result Say That You Are Very Serious In Your Study Go on");
          comtMark.setForeground(java.awt.Color.blue);
          reSrc.setVisible(false);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        }else if(Result>=3.40 && Result<=3.79){
          comtMark.setText("Very Good Result, You Try Your Best, Go On");
          comtMark.setForeground(java.awt.Color.DARK_GRAY);
           reSrc.setVisible(false);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        }else if(Result>=3.00 && Result<=3.39){
          comtMark.setText("Good Result, I Think Next Time You Will Do Better");
          comtMark.setForeground(java.awt.Color.yellow);
           reSrc.setVisible(false);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        }else if(Result>=2.50 && Result<=2.99){
          comtMark.setText("Satisfactory Result, I Think You Need Little Bit Study, So You Can Press This Button");
          comtMark.setForeground(java.awt.Color.black);
          reSrc.setVisible(true);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        }else if(Result>=2.00 && Result<=2.49){
          comtMark.setText("Lower Result, I Think You Need More Study , So You Can Press This Button");
          comtMark.setForeground(java.awt.Color.black);
          reSrc.setVisible(true);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        } else if(Result>=0.00 && Result<=1.99){
          comtMark.setText("Study Hard");
          comtMark.setForeground(java.awt.Color.RED);
          reSrc.setVisible(true);
          //comtSug.setText("You are Very Serious In your Study Best Of Luck");
        }  
         
           
           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        if(name.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Type your name Before Genarating & Printing Your Mark Sheet/Log!");
        }
        else if(resultDisp.getText().equals("")){
          JOptionPane.showMessageDialog(null,"I Think You do Not Calculate Your Result! Calculate Now Than Print");
        }
        else if(resultDisp.getText().equals("NaN")){
          JOptionPane.showMessageDialog(null,"I Think Your Result is [Nan]! Properly Calculate and Print");
        }
        else{
        
        String fileWrite = name.getText()+".txt";
        try {
            BufferedWriter writer ; 
             
            writer = new BufferedWriter (new FileWriter(fileWrite));
            
            writer.write("Mark Sheet Log Prepared By National University SGPA Calculator");
            writer.newLine();
            writer.newLine();
            //For Name Write
            writer.write("Your Name:"+" "+name.getText());
            writer.newLine();
            writer.newLine();
            //For Sub1
            writer.write("Subject 1 Grade: " +(String) subOne.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 1 Credit Hour: " +(String) subOneCre.getSelectedItem());
            writer.newLine();
            //For Sub2
            writer.write("Subject 2 Grade: " +(String) subTwo.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 2 Credit Hour: " +(String) subTwoCre.getSelectedItem());
            writer.newLine();
            //For Sub3
            writer.write("Subject 3 Grade: " +(String) subThree.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 3 Credit Hour: " +(String) subThreeCre.getSelectedItem());
            writer.newLine();
            //For Sub4
            writer.write("Subject 4 Grade: " +(String) subFour.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 4 Credit Hour: " +(String) subFourCre.getSelectedItem());
            writer.newLine();
            //For Sub5
            writer.write("Subject 5 Grade: " +(String) subFive.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 5 Credit Hour: " +(String) subFiveCre.getSelectedItem());
            writer.newLine();
            //For Sub6
            writer.write("Subject 6 Grade: " +(String) subSix.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 6 Credit Hour: " +(String) subSixCre.getSelectedItem());
            writer.newLine();
            //For Sub7
            writer.write("Subject 7 Grade: " +(String) subSeven.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 7 Credit Hour: " +(String) subSevenCre.getSelectedItem());
            writer.newLine();
            //For Sub8
            writer.write("Subject 8 Grade: " +(String) subEight.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 8 Credit Hour: " +(String) subEightCre.getSelectedItem());
            writer.newLine();
            //For Sub9
            writer.write("Subject 9 Grade: " +(String) subNine.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 9 Credit Hour: " +(String) subNineCre.getSelectedItem());
            writer.newLine();
            //For Sub10
            writer.write("Subject 10 Grade: " +(String) subTen.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 10 Credit Hour: " +(String) subTenCre.getSelectedItem());
            writer.newLine();
            //For Sub11
            writer.write("Subject 11 Grade: " +(String) subTwelve.getSelectedItem());
            writer.write("   ");
            writer.write("Subject 11 Credit Hour: " +(String) subTwelveCre.getSelectedItem());
            writer.newLine();
            writer.newLine();
           //For Result
            
            writer.write("Your Result: " +resultDisp.getText());
            writer.newLine();
            
           //For Comment
            writer.newLine();
            writer.write("Best Of Luck");
           
            
            writer.close();
            
            JOptionPane.showMessageDialog(null, "Your Result Printed Successfully! You can get Your File where Your Application is Situated");
        } catch (Exception e) {
        }
      }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        resultDisp.setText("");
        comtMark.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void reSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reSrcActionPerformed
        nusgapcalc.Assistor openAssistor = new nusgapcalc.Assistor();
        openAssistor.setVisible(true);
    }//GEN-LAST:event_reSrcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         nusgapcalc.CalcChart openCalcChart = new nusgapcalc.CalcChart();
         openCalcChart.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         nusgapcalc.Assistor openAssistor = new nusgapcalc.Assistor();
        openAssistor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       About openAbout = new About();
       openAbout.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        resultDisp.setText("");
        name.setText("");
        comtMark.setText("");
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UISgpaNU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UISgpaNU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UISgpaNU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UISgpaNU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UISgpaNU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comtMark;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField name;
    private javax.swing.JButton reSrc;
    private javax.swing.JTextField resultDisp;
    private javax.swing.JComboBox<String> subEight;
    private javax.swing.JComboBox<String> subEightCre;
    private javax.swing.JComboBox<String> subFive;
    private javax.swing.JComboBox<String> subFiveCre;
    private javax.swing.JComboBox<String> subFour;
    private javax.swing.JComboBox<String> subFourCre;
    private javax.swing.JComboBox<String> subNine;
    private javax.swing.JComboBox<String> subNineCre;
    private javax.swing.JComboBox<String> subOne;
    private javax.swing.JComboBox<String> subOneCre;
    private javax.swing.JComboBox<String> subSeven;
    private javax.swing.JComboBox<String> subSevenCre;
    private javax.swing.JComboBox<String> subSix;
    private javax.swing.JComboBox<String> subSixCre;
    private javax.swing.JComboBox<String> subTen;
    private javax.swing.JComboBox<String> subTenCre;
    private javax.swing.JComboBox<String> subThree;
    private javax.swing.JComboBox<String> subThreeCre;
    private javax.swing.JComboBox<String> subTwelve;
    private javax.swing.JComboBox<String> subTwelveCre;
    private javax.swing.JComboBox<String> subTwo;
    private javax.swing.JComboBox<String> subTwoCre;
    // End of variables declaration//GEN-END:variables
}
